// GENERATED by scripts/generate-post-dates.ts — do not edit by hand.
// Regenerated on every build (see the "prebuild" script in package.json).
//
// dateModified for each blog post, read from the git commit that last touched
// its component — the same source generate-sitemap.ts uses for <lastmod>, so
// the Article schema and the sitemap can no longer disagree.

/** Post path (no trailing slash) -> ISO date the post was last revised. */
export const POST_MODIFIED: Readonly<Record<string, string>> = {
  "/blog/choosing-cleaning-company": "2026-08-28",
  "/blog/cleaning-schedule": "2026-08-29",
  "/blog/cleaning-services-calgary": "2026-08-28",
  "/blog/spotless-home-tips": "2026-08-28",
  "/cleaning-with-vinegar-and-baking-soda": "2026-08-28",
  "/how-much-does-a-house-cleaning-cost": "2026-08-28",
  "/how-often-should-a-cleaning-service-clean-my-house": "2026-08-28",
  "/the-top-5-must-have-cleaning-products-for-a-spotless-home": "2026-08-28",
};

/**
 * dateModified for a post, falling back to its publication date.
 *
 * The fallback matters: a post added to the site but not yet to the POSTS map
 * in the generator would otherwise render `undefined` into JSON-LD, which is
 * worse than a slightly stale date.
 */
export function modifiedFor(path: string, datePublished: string): string {
  const clean = path.replace(/\/+$/, "") || "/";
  return POST_MODIFIED[clean] ?? datePublished;
}
