/** Emit article revision dates from the reviewed rendered-content ledger. */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import revisions from "../src/data/content-revisions.json";
import { POST_PUBLISHED } from "../src/data/post-published";

const entries = Object.keys(POST_PUBLISHED).sort().map(slug => {
  const revision = revisions[slug as keyof typeof revisions];
  if (!revision) throw new Error(`Missing reviewed content date for ${slug}; run content-dates after prerendering`);
  return `  "${slug}": "${revision.modified}",`;
}).join("\n");

writeFileSync(resolve("src/data/post-dates.ts"), `// GENERATED by scripts/generate-post-dates.ts — do not edit by hand.
// Dates come from content-revisions.json, also used by the sitemap generator.
// Approve substantive rendered changes with bun run content-dates --approve YYYY-MM-DD.
export const POST_MODIFIED: Readonly<Record<string, string>> = {
${entries}
};

export function modifiedFor(path: string, datePublished: string): string {
  const clean = path.replace(/\\/+$/, "") || "/";
  return POST_MODIFIED[clean] ?? datePublished;
}
`, "utf8");
console.log(`generate-post-dates: wrote ${Object.keys(POST_PUBLISHED).length} reviewed post dates`);
