/**
 * Writes src/data/post-dates.ts — the `dateModified` for every blog post,
 * taken from the git commit that last touched that post's component.
 *
 * WHY THIS EXISTS
 * All eight posts hardcoded `dateModified` equal to `datePublished`, so no post
 * had ever been marked as revised. Meanwhile generate-sitemap.ts derives
 * <lastmod> from git, and several of these posts HAVE been revised. The two
 * outputs therefore contradicted each other on every single post, by as much as
 * seven months:
 *
 *     /blog/choosing-cleaning-company/   schema 2026-01-27   sitemap 2026-08-28
 *     /cleaning-with-vinegar-and-baking-soda/  2026-01-25    sitemap 2026-08-28
 *     ...and six more
 *
 * Google reads both. The schema said "untouched since January" while the
 * sitemap said "revised last week", and the sitemap was the accurate one.
 * Freshness is a live input for advice content, so the stale half was actively
 * working against the pages.
 *
 * datePublished stays hand-written in each post — it is a fact about when the
 * article first appeared and git cannot know it (the repo is younger than some
 * of this content, which was migrated from WordPress).
 *
 * WHY IT IS COMMITTED RATHER THAN GITIGNORED
 * The prebuild step regenerates it, but the file is checked in so a clean
 * checkout, a CI run with a shallow clone, or anything that builds without git
 * still gets real dates instead of a crash. That means editing a post leaves
 * this file one commit behind until the next build regenerates it — the same
 * one-commit lag generate-sitemap.ts already accepts, and the same direction of
 * error (slightly stale, never invented).
 */
import { execSync } from "node:child_process";
import { writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

/** slug used as the key -> the component whose git history dates the post. */
const POSTS: Record<string, string> = {
  "/blog/choosing-cleaning-company": "src/pages/BlogChoosingCleaningCompany.tsx",
  "/blog/cleaning-schedule": "src/pages/BlogCleaningSchedule.tsx",
  "/blog/cleaning-services-calgary": "src/pages/BlogChoosingCalgaryCleaner.tsx",
  "/blog/spotless-home-tips": "src/pages/BlogSpotlessHomeTips.tsx",
  "/cleaning-with-vinegar-and-baking-soda": "src/pages/BlogVinegarBakingSoda.tsx",
  "/how-much-does-a-house-cleaning-cost": "src/pages/BlogHouseCleaningCost.tsx",
  "/how-often-should-a-cleaning-service-clean-my-house": "src/pages/BlogCleaningFrequency.tsx",
  "/the-top-5-must-have-cleaning-products-for-a-spotless-home": "src/pages/BlogCleaningProducts.tsx",
};

function repoLastCommit(): string {
  try {
    return execSync("git log -1 --format=%cs", { encoding: "utf8" }).trim();
  } catch {
    return new Date().toISOString().slice(0, 10);
  }
}

const fallback = repoLastCommit();

function lastModified(file: string): string {
  if (!existsSync(resolve(file))) {
    throw new Error(`generate-post-dates: ${file} does not exist — fix the POSTS map`);
  }
  try {
    const out = execSync(`git log -1 --format=%cs -- "${file}"`, { encoding: "utf8" }).trim();
    // An uncommitted new file has no log entry; the repo date is the honest
    // answer there, not a fabricated one.
    return out || fallback;
  } catch {
    return fallback;
  }
}

const entries = Object.entries(POSTS)
  .map(([slug, file]) => `  "${slug}": "${lastModified(file)}",`)
  .join("\n");

const body = `// GENERATED by scripts/generate-post-dates.ts — do not edit by hand.
// Regenerated on every build (see the "prebuild" script in package.json).
//
// dateModified for each blog post, read from the git commit that last touched
// its component — the same source generate-sitemap.ts uses for <lastmod>, so
// the Article schema and the sitemap can no longer disagree.

/** Post path (no trailing slash) -> ISO date the post was last revised. */
export const POST_MODIFIED: Readonly<Record<string, string>> = {
${entries}
};

/**
 * dateModified for a post, falling back to its publication date.
 *
 * The fallback matters: a post added to the site but not yet to the POSTS map
 * in the generator would otherwise render \`undefined\` into JSON-LD, which is
 * worse than a slightly stale date.
 */
export function modifiedFor(path: string, datePublished: string): string {
  const clean = path.replace(/\\/+$/, "") || "/";
  return POST_MODIFIED[clean] ?? datePublished;
}
`;

writeFileSync(resolve("src/data/post-dates.ts"), body, "utf8");
console.log(`generate-post-dates: wrote ${Object.keys(POSTS).length} post dates`);
