/**
 * Every guard, and the one edit that must make it fail.
 *
 * Five guards in this repository passed for weeks while catching nothing: one
 * counted filenames instead of reading them, one compared a CSP against a
 * copy of itself, and three had their regexes mangled in transit (`\b` became
 * a backspace, `\r?\n` a real newline) so they matched nothing and asserted
 * "no matches" — which is exactly what a clean site also looks like.
 *
 * A guard is only known to work at the moment it has been seen to fail. So
 * each entry here names a target file, an exact edit that reintroduces the
 * defect the guard exists for, and the test that must then fail. The runner
 * (prove-guards.ts) applies each one, runs the guard, checks it failed for
 * the stated reason, and restores the file. The vitest side
 * (guard-proofs.test.ts) checks, cheaply and on every run, that every guard
 * file has an entry and that every `find` still occurs exactly once — so a
 * refactor cannot silently turn a proof into a no-op either.
 *
 * Add a guard, add its proof. The suite fails otherwise.
 */

export interface GuardProof {
  /** The test file this proves, relative to the site root. */
  guard: string;
  /** The file to break, relative to the site root. */
  target: string;
  /** Exact text to replace; must occur exactly once in the target. */
  find: string;
  replace: string;
  /** The `it(...)` title (or a tsc error fragment) that must then fail. */
  failing: string;
  /** What defect this reintroduces, in one sentence. */
  why: string;
  /** How the failure is detected. Defaults to running the guard with vitest. */
  check?: "vitest" | "tsc";
  /** The target lives in dist/, so the site must be built and prerendered. */
  dist?: boolean;
}

export const GUARD_PROOFS: GuardProof[] = [
  { guard: "src/data/seo-editorial.test.ts", target: "src/data/service-copy.ts", find: "some marks may remain", replace: "every mark disappears", failing: "qualifies wall-washing results in the shared description", why: "Reintroduces an unconditional wall-washing result promise." },
  { guard: "src/data/seo-editorial.test.ts", target: "scripts/content-revisions.ts", find: "if (previous?.hash === hash) return previous;", replace: "if (false) return previous;", failing: "does not change revision dates for CSS or date-only edits", why: "Advances a revision date even though the content fingerprint is unchanged." },
  { guard: "src/lib/form-health.test.ts", target: "src/lib/form-health.ts", find: "path: currentPath(),", replace: 'path: "/?email=customer@example.com",', failing: "reports fixed diagnostics without form values or URL parameters", why: "Leaks a customer's email-shaped query value into the operational alert." },
  { guard: "src/lib/form-health-php.test.ts", target: "public/api/form-health.php", find: "$allowedKeys = ['event', 'form', 'stage', 'category', 'status', 'path'];", replace: "$allowedKeys = ['event', 'form', 'stage', 'category', 'status', 'path', 'email'];", failing: "accepts authenticated server reports and rejects foreign browsers or extra data", why: "Allows a customer email field into the monitoring request contract." },
  { guard: "src/lib/siteground-handoff.test.ts", target: "public/api/booking-handoff.php", find: "if (!$isWebsite && !$isBooking) {", replace: "if (false) {", failing: "keeps the SiteGround endpoint origin-bound, expiring and self-hosted", why: "Accepts requests from an unapproved origin." },
  { guard: "src/lib/booking-handoff.test.ts", target: "src/lib/booking-details.ts", find: "if (!details.address?.trim())", replace: "if (false)", failing: "matches native questions and requires the complete address and flexibility after price", why: "Drops the required service address." },
  { guard: "src/lib/booking-handoff.test.ts", target: "src/lib/booking-redirect.ts", find: 'details.entry === "lockbox" ? "Entry: Key in a lockbox." : ""', replace: '""', failing: "transfers every new field without changing lockbox meaning or truncating its note", why: "Loses the lockbox explanation in native Other." },
  { guard: "src/lib/booking-handoff.test.ts", target: "src/lib/booking-handoff.ts", find: '"dc_notes", "dc_addr", "dc_apt"', replace: '"dc_notes", "dc_apt"', failing: "separates all personal fields from navigation and strips arbitrary parameters", why: "Drops the address from the private handoff." },
  { guard: "src/lib/booking-handoff.test.ts", target: "src/lib/booking-handoff.ts", find: "if (!response.ok) {", replace: "if (response.ok) {", failing: "uses a bounded encrypted handoff and never falls back to a personal-data URL", why: "Rejects successful sealing responses." },
  { guard: "src/lib/siteground-handoff.test.ts", target: "public/api/booking-handoff.php", find: "$payload['expires'] <= $now", replace: "$payload['expires'] < $now - DC_HANDOFF_TTL_MS", failing: "keeps the SiteGround endpoint origin-bound, expiring and self-hosted", why: "Accepts an expired personal-data capability." },
  { guard: "src/lib/booking-handoff.test.ts", target: "src/lib/booking-redirect.ts", find: 'params.set("service_id", String(serviceId));', replace: 'params.set("service_id", "1");', failing: "preserves every mapped room, home and frequency selection", why: "Sends the wrong service for all combinations." },
  { guard: "src/lib/booking-prefill.test.ts", target: "../bk-prefill-v2.js", find: "el.dispatchEvent(new Event('blur', { bubbles: true }));", replace: "/* no validation event */", failing: "fills text and native dropdowns and requires two stable readbacks", why: "Drops a validation event needed by the field adapter." },
  { guard: "src/lib/booking-prefill.test.ts", target: "../bk-prefill-v2.js", find: "if (edited[key] || document.activeElement === el)", replace: "if (false)", failing: "preserves existing data and never overwrites a customer's later edit", why: "Overwrites a customer's revised postal code." },
  { guard: "src/lib/booking-prefill.test.ts", target: "../bk-prefill-v2.js", find: "var duration = 20 * 60 * 1000", replace: "var duration = 30000", failing: "fills late-mounted controls after 30 seconds and repairs a bounded rerender", why: "Stops before delayed fields appear." },
  { guard: "src/lib/booking-prefill.test.ts", target: "../bk-prefill-v2.js", find: "lockbox: /^other\\b/i", replace: "lockbox: /^key will be in the mailbox$/i", failing: "maps lockbox to Other with explicit notes and supports every flexibility value", why: "Reintroduces the mailbox/lockbox mismatch." },
  { guard: "src/lib/booking-prefill.test.ts", target: "../bk-prefill-v2.js", find: "return list.length === 1 ? list[0] : null;", replace: "return list.length >= 1 ? list[0] : null;", failing: "rejects ambiguous fields and leaves payment and submission untouched", why: "Writes to an ambiguous address field." },
  {
    guard: "src/data/editorial-roles.test.ts",
    target: "src/components/ServiceIntentComparison.tsx",
    find: "microwave inside and out",
    replace: "microwave outside only",
    failing: "service comparisons keep the standard microwave inclusion accurate",
    why: "Makes the new comparison table contradict the confirmed standard-clean microwave inclusion.",
  },
  // ---- published prices --------------------------------------------------
  {
    guard: "src/data/published-prices.test.ts",
    target: "src/pages/locations/Sunalta.tsx",
    find: "priceRange: sitePriceRange(),",
    replace: 'priceRange: "$155-$539",',
    failing: "no page under src/pages hand-types a dollar figure unless it says why",
    why: "Retypes the band one location page derived, the defect 63 pages carried.",
  },
  {
    guard: "src/data/published-prices.test.ts",
    target: "src/data/gift-cards.ts",
    find: "rows.filter((r) => dollars(r) <= amount).at(-1) ?? null;",
    replace: "rows.filter((r) => dollars(r) <= amount).at(0) ?? null;",
    failing: "each gift card label promises only what its amount pays for",
    why: "Makes a gift-card label name the smallest home it covers instead of the largest.",
  },
  {
    guard: "src/data/published-prices.test.ts",
    target: "src/data/published-prices.test.ts",
    find: "const ALLOWED_LITERALS: Record<string, string> = {",
    replace: 'const ALLOWED_LITERALS: Record<string, string> = {\n  "Sunalta.tsx": "a stale entry excusing a file that has no literal",',
    failing: "every allowlisted page still contains the literal it is excused for",
    why: "An allowlist entry that matches nothing is a hole waiting for the next typed price.",
  },

  // ---- policy and provenance ---------------------------------------------
  {
    guard: "src/data/policy.test.ts",
    target: "src/data/policy.ts",
    find: 'guaranteeWindowHours: confirm(24, { by: "owner", on: "2026-08-24" }),',
    replace: 'guaranteeWindowHours: confirm(48, { by: "owner", on: "2026-08-24" }),',
    failing: "is 24 hours",
    why: "Reopens the 24-versus-48-hour guarantee drift at the one constant every surface reads.",
  },
  {
    guard: "src/data/policy.test.ts",
    target: "src/data/policy.ts",
    find: 'guaranteeWindowHours: confirm(24, { by: "owner", on: "2026-08-24" }),',
    replace: "guaranteeWindowHours: 24,",
    failing: "is not assignable to type 'Confirmed<number>'",
    why: "A bare literal in a Confirmed slot must not compile; that is what the brand is for.",
    check: "tsc",
  },
  {
    guard: "src/data/policy.test.ts",
    target: "src/data/policy.ts",
    find: '${money(travelFee("post-construction"))} for post-construction',
    replace: "$45 for post-construction",
    failing: "every dollar figure in policy.ts is either confirmed or derived",
    why: "Hand-types a bk-config figure back into the file that exists to stop that.",
  },

  // ---- the rest of the suite, one proof each -----------------------------
  {
    guard: "src/data/accessibility.test.ts",
    target: "src/components/CityIncludedChapter.tsx",
    find: "grid grid-cols-[2.5rem_minmax(0,1fr)] items-start gap-4",
    replace: "grid grid-cols-[2.5rem_minmax(0,11rem)_minmax(0,1fr)] items-start gap-4",
    failing: "does not reserve the desktop three-track grid below md",
    why: "Puts the 11rem title track back on the all-widths grid, the mobile clipping regression.",
  },
  {
    guard: "src/data/addon-table.test.ts",
    target: "src/data/addon-table.ts",
    find: 'const label = city === "calgary" ? "Outside Calgary (travel fee)" : "Outside Edmonton (travel fee)";',
    replace: 'const label = city === "calgary" ? "Outside Edmonton (travel fee)" : "Outside Calgary (travel fee)";',
    failing: "names the correct city on the travel-fee row",
    why: "Makes the Calgary add-on table say Edmonton on its travel-fee row.",
  },
  {
    guard: "src/data/blog-posts.test.ts",
    target: "src/pages/BlogVinegarBakingSoda.tsx",
    find: '"dateModified": modifiedOr("/cleaning-with-vinegar-and-baking-soda"),',
    replace: '"dateModified": "2026-01-25",',
    failing: "no post reintroduces a hand-typed dateModified",
    why: "Reintroduces a hand-typed modification date in a post's schema.",
  },
  {
    guard: "src/data/city-twins.test.ts",
    target: "dist/calgary/pricing/index.html",
    find: '<main id="main-content" tabindex="-1">',
    replace: '<main id="main-content" tabindex="-1"></main>',
    failing: "/calgary/pricing/ says something /pricing/ does not",
    why: "Empties the Calgary pricing body so it says nothing its Edmonton twin does not.",
    dist: true,
  },
  {
    guard: "src/data/claims-and-links.test.ts",
    target: "public/llms.txt",
    find: "a $29.99 travel fee is added to cleaning bookings",
    replace: "a $99 travel fee is added to cleaning bookings",
    failing: "every surface quoting a travel fee quotes the authority's amount",
    why: "Restores the $99-versus-$29.99 travel-fee drift on the machine-reader surface.",
  },
  {
    guard: "src/data/headers.test.ts",
    target: "index.html",
    find: 'document.documentElement.removeAttribute("data-motion")},4000);',
    replace: 'document.documentElement.removeAttribute("data-motion")},5000);',
    failing: "pins the current hash of the inline bootstrap script",
    why: "Changes one character of the inline script so the CSP hash in _headers no longer matches.",
  },
  {
    guard: "src/data/htaccess-parity.test.ts",
    target: "public/.htaccess",
    find: "RewriteRule ^services/commercial-cleaning/?$ /commercial-cleaning/ [R=301,L]",
    replace: "RewriteRule ^services/commercial-cleaning/?$ /commercial-cleaning-services-calgary/ [R=301,L]",
    failing: "every Netlify redirect has an Apache equivalent, and vice versa",
    why: "Repoints one Apache rule so the two generated rule sets disagree.",
  },
  {
    guard: "src/data/htaccess-parity.test.ts",
    target: "public/.htaccess",
    find: "  RewriteCond %{HTTPS} !=on\n  RewriteCond %{HTTP:X-Forwarded-Proto} !=https\n",
    replace: "  RewriteCond %{HTTPS} !=on [OR]\n  RewriteCond %{HTTP:X-Forwarded-Proto} =http\n",
    failing: "does not redirect a request that is already HTTPS behind the proxy",
    why: "Restores the OR'd HTTPS conditions that loop behind a TLS-terminating proxy.",
  },
  {
    guard: "src/data/internal-links.test.ts",
    target: "dist/locations/allendale/index.html",
    find: 'hover:text-accent" href="/edmonton/deep-cleaning/"',
    replace: 'hover:text-accent" href="/calgary/deep-cleaning/"',
    failing: "no location page links to the other city's service pages",
    why: "Makes an Edmonton location page link to a Calgary service page.",
    dist: true,
  },
  {
    guard: "src/data/legacy-families.test.ts",
    target: "src/data/legacy-urls.ts",
    find: 'legacy: "/cleaning-services-for-leduc-ab"',
    replace: 'legacy: "/cleaning-services-for-leduc-ab-old"',
    failing: "every /cleaning-services-for-… URL Search Console knows about is mapped",
    why: "Drops Leduc, the family member that hid in 'Crawled - currently not indexed'.",
  },
  {
    guard: "src/data/llms-txt.test.ts",
    target: "public/llms.txt",
    find: "[FAQ](https://dutycleaners.ca/faqs/): Answers to common cleaning questions",
    replace: "[FAQ](https://dutycleaners.ca/faqs): Answers to common cleaning questions",
    failing: "every page link is trailing-slash canonical",
    why: "Strips the trailing slash from one machine-reader link on a slash-canonical site.",
  },
  {
    guard: "src/data/localization.test.ts",
    target: "dist/locations/allendale/index.html",
    find: "A standard clean in Allendale runs",
    replace: "A standard clean in Edmonton runs",
    failing: "the injected place name in the pricing prose is the page's own",
    why: "Names the city instead of the page's own place in the pricing prose.",
    dist: true,
  },
  {
    guard: "src/data/location-directory.test.ts",
    target: "src/data/location-directory.ts",
    find: "  if (city) return BY_CITY[city].get(key) ?? null;",
    replace: "  if (city) return BY_CITY[city].get(key) ?? ANY_CITY.get(key) ?? null;",
    failing: "returns null rather than linking across cities",
    why: "Restores the cross-city fallback that sent a Calgary chip to an Edmonton page.",
  },
  {
    guard: "src/data/location-geo.test.ts",
    target: "src/data/location-geo.ts",
    find: '"/locations/spruce-avenue": { latitude: "53.56440", longitude: "-113.49842" },',
    replace: '"/locations/spruce-avenue": { latitude: "53.54610", longitude: "-113.49380" },',
    failing: "no pin has fallen back to a bare city centre",
    why: "Moves one pin onto the Edmonton centroid, the geocoder's city-centre fallback signature.",
  },
  {
    guard: "src/data/location-pages.test.ts",
    target: "dist/locations/allendale/index.html",
    find: '"@type":"BreadcrumbList"',
    replace: '"@type":"BreadcrumbLst"',
    failing: "every page emits BreadcrumbList",
    why: "Removes the breadcrumb schema from one built page.",
    dist: true,
  },
  {
    guard: "src/data/onpage-seo.test.ts",
    target: "dist/faqs/index.html",
    find: "<title>House Cleaning FAQs | Duty Cleaners Alberta</title>",
    replace: "<title>House Cleaning Frequently Asked Questions for Homeowners Across Edmonton &amp; Calgary | Duty Cleaners</title>",
    failing: "titles and descriptions fit the width Google gives a snippet",
    why: "Pushes a built title past the pixel width a snippet gets.",
    dist: true,
  },
  {
    guard: "src/data/pricing.test.ts",
    target: "src/data/pricing.ts",
    find: "price: displayPrice(money(standard + packagePrice)),",
    replace: "price: displayPrice(money(standard)),",
    failing: "prices a deep clean as Standard plus the Deep Cleaning package",
    why: "Publishes the deep tier without the package price bk-config adds to it.",
  },
  {
    guard: "src/data/quote-intent.test.ts",
    target: "src/hooks/use-quote-overlay.tsx",
    find: "const intentInHref = /[?&]intent=deep(?:[&#]|$)/.test(rawHref);",
    replace: "const intentInHref = false;",
    failing: "the interceptor reads the intent from the href, not only a data attribute",
    why: "Stops the quote interceptor reading intent=deep from the CTA href.",
  },
  {
    guard: "src/data/recurring-quote.test.ts",
    target: "src/data/pricing.ts",
    find: "const recurringAddOns = chosen.filter((addOn) => !addOn.firstVisitOnly);",
    replace: "const recurringAddOns = chosen;",
    failing: "leaves a first-visit-only extra out of the recurring price entirely",
    why: "Bills a first-visit-only extra on every recurring visit.",
  },
  {
    guard: "src/data/rendered-quality.test.ts",
    target: "dist/cleaning-services-st-albert/index.html",
    find: "house cleaning in St. Albert costs, worked through",
    replace: "house cleaning in St Albert costs, worked through",
    failing: "no banned grammar artifact appears on any rendered page",
    why: "Reintroduces the de-slugged 'St Albert' in rendered prose.",
    dist: true,
  },
  {
    guard: "src/data/service-radius.test.ts",
    target: "dist/index.html",
    find: "Inside Edmonton city limits there is no trip fee, in any of the 80 neighbourhoods the Edmonton branch covers.",
    replace: "Inside Edmonton city limits there is no trip fee, in any of the 80 neighbourhoods the Edmonton branch covers within a 30km radius.",
    failing: "no built page states a radius its own coordinates contradict",
    why: "States a 30 km radius that location-geo.ts contradicts (Stony Plain is 33.8 km out).",
    dist: true,
  },
  {
    guard: "src/data/structured-data.test.ts",
    target: "dist/contact-us/index.html",
    find: '"https://x.com/Dutycleaners"],"telephone":"+1-780-913-6565"',
    replace: '"https://x.com/Dutycleaners"],"telephone":"+1-7809136565"',
    failing: "every schema telephone is one of the two real numbers, in one format",
    why: "Reintroduces the unformatted E.164 that gave one @id two phone numbers.",
    dist: true,
  },
  {
    guard: "src/lib/booking-redirect.test.ts",
    target: "src/lib/booking-redirect.ts",
    find: "bedrooms: [1, { 1: 87, 2: 81, 3: 82, 4: 83, 5: 84, 6: 85, 7: 86 }],",
    replace: "bedrooms: [1, { 1: 87, 2: 81, 3: 83, 4: 83, 5: 84, 6: 85, 7: 86 }],",
    failing: "matches the reference example exactly",
    why: "Sends BookingKoala the 4-bedroom option id for a 3-bedroom home.",
  },
  {
    guard: "src/lib/quote-submit.test.ts",
    target: "src/lib/quote-submit.ts",
    find: "const hasDurableReceipt = Boolean(result?.ok && result?.stored && result?.receiptId);",
    replace: "const hasDurableReceipt = Boolean(result?.ok && result?.stored);",
    failing: "classifies a response without a verifiable receipt as failed capture",
    why: "Misclassifies an unverified response as a successful lead capture.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/components/quote/QuoteFlow.tsx",
    find: "setLeadCaptureFailed(true);\n    setStep(2);",
    replace: "setLeadCaptureFailed(true);\n    return;",
    failing: "shows the calculated price with accurate stage-specific recovery copy",
    why: "Hides the locally calculated price when the external lead relay fails.",
  },
  {
    guard: "src/lib/city-from-path.test.ts",
    target: "src/lib/city-from-path.ts",
    find: 'if (/(^|[/-])calgary($|[/-])/.test(path)) return "calgary";',
    replace: 'if (path.startsWith("/calgary")) return "calgary";',
    failing: "treats the canonical Calgary landing URL as Calgary",
    why: "Restores the startsWith bug that put Edmonton's phone on the biggest Calgary page.",
  },
  {
    guard: "src/lib/google-listings.test.ts",
    target: "src/lib/google-listings.ts",
    find: '"8192121191672692049",',
    replace: '"8192121191672692040",',
    failing: "edmonton: the Place ID encodes the CID it is paired with",
    why: "Breaks the CID / Place ID pairing a review link depends on.",
  },
  {
    guard: "src/lib/schema-url.test.ts",
    target: "src/lib/pricing-schema.ts",
    find: 'url: canonicalUrlForPath("/calgary/pricing"),',
    replace: 'url: "https://dutycleaners.ca/calgary/pricing",',
    failing: "the pricing builder publishes a slash-canonical url for both cities",
    why: "Retypes the Calgary pricing URL without its trailing slash, so the Service node names a 301.",
  },

  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/components/CityCoverageGrid.tsx",
    find: 'intro = "Each name links to its own page. For an address that is not listed, call the branch.",',
    replace: 'intro = "Say goodbye to dirt. Each name links to its own page. For an address that is not listed, call the branch.",',
    failing: "no page or component carries filler that was only ever template noise",
    why: "Reintroduces a stock closer on a hub component that 146 pages render.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/pages/locations/Leduc.tsx",
    // Was the About-section line "Many households here work a rotation rather
    // than a weekday." That sentence said the page's one local insight for the
    // second of three times and was cut; the insight now lives once, here, in
    // the local note. The proof follows it.
    find: "Leduc sits 33 km south of Edmonton and directly beside the international airport,",
    replace: "Leduc is a thriving city. Leduc sits 33 km south of Edmonton and directly beside the international airport,",
    failing: "the money pages carry none of the brochure vocabulary",
    why: "Puts the brochure register back on the town page where a reader lands first.",
  },
  {
    guard: "src/data/money-page-seo.test.ts",
    target: "dist/move-out-cleaning-edmonton/index.html",
    find: "<title>Move Out Cleaning Edmonton from $284 | Duty Cleaners</title>",
    replace: "<title>Welcome | Duty Cleaners</title>",
    failing: "title identifies the intended service and place within the project's copy budget",
    why: "Removes the service and city from a money-page title, making the target unclear. A price hook is optional.",
    dist: true,
  },
  {
    guard: "src/data/page-weight.test.ts",
    target: "src/data/page-weight.test.ts",
    find: "  js_gzip_kb: 170,",
    replace: "  js_gzip_kb: 17,",
    failing: "scripts total under 17 KB gzipped",
    why: "Asset names are hashed per build, so the proof tightens the budget and shows the measurement is real: every page's scripts weigh more than 17 KB.",
    // The target is the guard itself, but the guard only measures a built site.
  },
  {
    guard: "src/data/page-weight.test.ts",
    target: "src/data/page-weight.test.ts",
    find: "  image_kb: 100,",
    replace: "  image_kb: 10,",
    failing: "no body image is over 10 KB",
    why: "Tightens the per-image cap the same way, proving the cap reads real bytes: the 133 KB body photo the total-image budget hid would land over any honest cap.",
  },
  {
    guard: "src/data/page-weight.test.ts",
    target: "src/data/page-weight.test.ts",
    find: 'const HIDES_ON_PHONES = "hidden";',
    replace: 'const HIDES_ON_PHONES = "relative";',
    failing: "does not make a phone download a hero it never renders",
    why: "Points the ancestor scan at a class every hero really does sit inside, so a scan that never walked the wrappers would still report nothing and be caught.",
  },
  {
    guard: "src/data/page-weight.test.ts",
    target: "src/data/page-weight.test.ts",
    find: 'const REVEAL_HIDDEN = "opacity-0 translate-y-8";',
    replace: 'const REVEAL_HIDDEN = "<main";',
    failing: "ships no scroll-reveal wrapper still in its hidden start state",
    why: "Points the search at a string every built page contains, so a check reading the wrong file — or no file — cannot pass by finding nothing.",
  },
  {
    guard: "src/data/page-weight.test.ts",
    target: "src/data/page-weight.test.ts",
    find: "  const CAP_KB = 100;",
    replace: "  const CAP_KB = 10;",
    failing: "every image asset is at most 10 KB",
    why: "Asset names are hashed per build, so the proof tightens the cap: it shows the scan really reads every image in dist, not an empty list.",
  },
  {
    guard: "src/data/onpage-seo.test.ts",
    target: "dist/index.html",
    find: '<meta charset="UTF-8">',
    replace: '<meta charset="UTF-8"><link rel="modulepreload" href="/assets/rival.js">',
    failing: "every hero preload comes before the stylesheet and every script preload",
    why: "Puts a script preload ahead of the hero image hint, the order Helmet produced before the prerender moved it.",
    dist: true,
  },
  // ---- FAQ answers are lifted alone --------------------------------------
  // One proof per banned term, each putting back a sentence that really
  // shipped inside FAQPage markup.
  {
    guard: "src/data/faq-answers.test.ts",
    target: "dist/calgary/deep-cleaning/index.html",
    find: 'each add a charge on the quote."}',
    replace: 'each add a charge on the quote. The table above lists every home size."}',
    failing: "no FAQ answer points at the rest of its page",
    why: "Restores the audited Calgary deep-clean answer, which sent a lifted reader to a table above it they cannot see.",
    dist: true,
  },
  // ---- the content-prompt rollout (DUTY-CLEANERS-CONTENT-PROMPT.md), 2026-09-10 ----
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/pages/locations/Mahogany.tsx",
    find: "Photos help but are not required.",
    replace: "Trusted by local families. Photos help but are not required.",
    failing: "no location page carries brochure vocabulary or a retired promise",
    why: "Puts a 'trusted by' line back on a neighbourhood page, where the money-page word list never reached.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/data/location-cards.tsx",
    find: 'title: "All supplies brought for you" }',
    replace: 'title: "All supplies brought for you", description: "Trusted by local families." }',
    failing: "no location page carries brochure vocabulary or a retired promise",
    why: "The cards all 163 location pages show live in one data file since 2026-09-18; a brochure line there would reach every page while the per-page scan saw nothing.",
  },
  {
    guard: "src/data/location-similarity.test.ts",
    target: "src/data/location-similarity.test.ts",
    find: "const MAX_NEAREST = 0.48;",
    replace: "const MAX_NEAREST = 0.3;",
    failing: "no location page shares close to half its phrases with another",
    why: "Similarity is a property of the whole build, so the proof lowers the ceiling: it shows the guard really reads and compares the prerendered location pages rather than an empty set.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/pages/EdmontonPricing.tsx",
    find: "Every 4 weeks comes to 13 visits a year rather than 12.",
    replace: "Every 4 weeks comes to 13 visits a year rather than 12, with a 100% satisfaction guarantee.",
    failing: "no money page makes a promise the content prompt retired",
    why: "Restores a '100% satisfaction' promise the re-clean guarantee (policy T1) does not make.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/pages/locations/Mahogany.tsx",
    find: "Tell us within 24 hours and the team comes back to your Mahogany home",
    replace: "Run a business in Mahogany? We also handle commercial and office cleaning. Tell us within 24 hours and the team comes back to your Mahogany home",
    failing: "no location page sells commercial cleaning",
    why: "Brings back the commercial-cleaning promo that seven neighbourhood pages ended on.",
  },
  {
    guard: "src/data/claims-and-links.test.ts",
    target: "dist/locations/mahogany/index.html",
    find: "Ready to Book a Clean in Mahogany?",
    replace: "Ready to Book a Clean in Mahogany? Same-day and next-day availability.",
    failing: "no house-cleaning page claims /same-day and next-day (?:availability|openings)/ — an unconditional same-day promise; the most the site says is that same-day and next-day slots depend on the schedule",
    why: "Restores the unconditional same-day card that ran on 150 neighbourhood pages.",
    dist: true,
  },
  {
    guard: "src/data/claims-and-links.test.ts",
    target: "dist/locations/mahogany/index.html",
    find: "Ready to Book a Clean in Mahogany?",
    replace: "Ready to Book a Clean in Mahogany? 100% satisfaction guaranteed.",
    failing: "no house-cleaning page claims /\\b100%\\s*satisf/ — the guarantee is a re-clean within 24 hours (policy T1), not a satisfaction promise",
    why: "Restores the '100% satisfaction' badge and FAQ that ran on 150 pages.",
    dist: true,
  },
  {
    guard: "src/data/claims-and-links.test.ts",
    target: "dist/locations/mahogany/index.html",
    find: "Ready to Book a Clean in Mahogany?",
    replace: "Ready to Book a Clean in Mahogany? Trusted by local families.",
    failing: "no house-cleaning page claims /\\btrusted by\\b/ — an endorsement no source backs",
    why: "Restores the 'trusted by' subtitle that ran on 158 pages.",
    dist: true,
  },
  {
    guard: "src/data/claims-and-links.test.ts",
    target: "dist/locations/mahogany/index.html",
    find: "Ready to Book a Clean in Mahogany?",
    replace: "Ready to Book a Clean in Mahogany? Our cleaners are fully insured.",
    failing: "no house-cleaning page claims /\\binsured\\b/ — no insurance fact exists in proof.ts or policy.ts",
    why: "Claims insurance, a fact nothing in the repository records.",
    dist: true,
  },
  {
    guard: "src/data/claims-and-links.test.ts",
    target: "dist/locations/mahogany/index.html",
    find: "Ready to Book a Clean in Mahogany?",
    replace: "Ready to Book a Clean in Mahogany? Cleaners trained to exacting quality standards.",
    failing: "no house-cleaning page claims /exacting quality standards/ — an unsourced quality claim",
    why: "Restores the 'exacting quality standards' card that ran on 132 pages.",
    dist: true,
  },
  {
    guard: "src/data/claims-and-links.test.ts",
    target: "dist/locations/mahogany/index.html",
    find: "Ready to Book a Clean in Mahogany?",
    replace: "Ready to Book a Clean in Mahogany? Here are the places that make Mahogany feel like home.",
    failing: "no house-cleaning page claims /feel like home/ — the landmark-tour sections the prompt retired as tourism",
    why: "Restores the landmark-tour intro that ran on 52 neighbourhood pages.",
    dist: true,
  },
  {
    guard: "src/data/location-pages.test.ts",
    target: "dist/locations/mahogany/index.html",
    find: "Ready to Book a Clean in Mahogany?",
    replace: "Ready to Book a Clean in Mahogany? Book today!",
    failing: "no location page's copy uses an exclamation mark",
    why: "Puts an exclamation mark back into a neighbourhood page's copy, as 146 pages had.",
    dist: true,
  },
  {
    guard: "src/data/faq-answers.test.ts",
    target: "dist/services/index.html",
    find: '"text":"No. Every price we quote in Edmonton,',
    replace: '"text":"No. Every figure on this page,',
    failing: "no FAQ answer points at the rest of its page",
    why: "Restores the audited GST answer, which named no price and pointed at this page instead.",
    dist: true,
  },
  {
    guard: "src/data/faq-answers.test.ts",
    target: "dist/how-much-does-a-house-cleaning-cost/index.html",
    find: '."}},{"@type":"Question","name":"Why do move-out and standard cleaning quotes differ?"',
    replace: '. The table below shows what that does to each tier."}},{"@type":"Question","name":"Why do move-out and standard cleaning quotes differ?"',
    failing: "no FAQ answer points at the rest of its page",
    why: "Restores the cost guide's recurring-table pointer, so the third banned word is seen to fail as well.",
    dist: true,
  },

  // ---- the owner's answers of 2026-09-10 ---------------------------------
  {
    guard: "src/data/rendered-quality.test.ts",
    target: "dist/reviews/index.html",
    find: "Alberta Bookings",
    replace: "Alberta Bookings, 4,000+ Edmonton homes cleaned",
    failing: "states volume only as the owner's confirmed bookings figure",
    why: "Restores the unconfirmed per-city homes figure the owner replaced with 5,000+ bookings.",
    dist: true,
  },
  {
    guard: "src/data/location-pages.test.ts",
    target: "dist/locations/black-diamond/index.html",
    find: ">Turner Valley (Diamond Valley)</a>",
    replace: ">Turner Valley</a>",
    failing: "every link to either half of Diamond Valley names the town",
    why: "Links Turner Valley from Black Diamond as if the two were still separate towns.",
    dist: true,
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/components/CityIncludedChapter.tsx",
    find: '"Hard floors mopped",',
    replace: '"Hard floors mopped", "Light switches & door handles",',
    failing: "light switches are in the deep package, not the standard checklist",
    why: "Puts light switches back on the standard checklist, which the owner keeps for the deep clean.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/components/quote/ServiceStartCard.tsx",
    find: 'to="/contact-us/#topic=airbnb" className="font-semibold',
    replace: 'to="/contact-us/" className="font-semibold',
    failing: "online quotes are for office cleaning only, and short-term rentals get a callback",
    why: "Sends Airbnb hosts to the general quote form again instead of the callback request.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/components/RecentActivityStrip.tsx",
    find: "            {BOOKINGS_CLAIM}",
    replace: "            4,000+ {city} homes cleaned",
    failing: "no page or component labels a figure as homes cleaned",
    why: "Restores the per-city homes figure in a strip that renders only in the browser, where the prerendered check cannot see it.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/components/LocationPageTemplate.tsx",
    find: "• Baseboards and doors wiped",
    replace: "• Ceiling fans dusted and cleaned",
    failing: "ceiling fans are an on-request extra, never part of a package",
    why: "Puts ceiling fans back in the deep package's FAQ list, as it read on 129 location pages.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/components/CityIncludedChapter.tsx",
    find: '"Hard floors mopped",',
    replace: '"Hard floors mopped", "Cobwebs removed",',
    failing: "cobwebs are in the deep package, not a standard or wall-washing list",
    why: "Puts cobwebs back on the hubs' standard checklist, which the owner keeps for the deep clean.",
  },
  {
    guard: "src/data/structured-data.test.ts",
    target: "dist/index.html",
    find: '"latitude":53.504317',
    replace: '"latitude":53.5',
    failing: "the hub's LocalBusiness geo equals proof.ts",
    why: "Publishes an Edmonton office pin that is not the one the owner confirmed.",
    dist: true,
  },
  {
    guard: "src/data/rendered-quality.test.ts",
    target: "dist/pricing/index.html",
    find: "from $65/hour",
    replace: "$60/hour",
    failing: "prices Airbnb turnovers at the turnover rate and other hourly work from the home rate",
    why: "Quotes the Airbnb turnover rate as the Edmonton price list's hourly-cleaning rate, as it did for a day.",
    dist: true,
  },
  {
    guard: "src/data/rendered-quality.test.ts",
    target: "dist/move-out-cleaning-edmonton/index.html",
    find: 'href="https://www.alberta.ca/ending-a-tenancy"',
    replace: 'href="https://www.alberta.ca/"',
    failing: "the pages that state official rules link their official source",
    why: "Drops the official source behind the Edmonton move-out page's tenancy-law sentence.",
    dist: true,
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/pages/Contact.tsx",
    find: '<SelectItem value="commercial">Office Cleaning</SelectItem>',
    replace: '<SelectItem value="commercial">Office & Commercial Cleaning</SelectItem>',
    failing: "online quotes are for office cleaning only, and short-term rentals get a callback",
    why: "Offers online quotes for all commercial work again, when the owner quotes only offices online.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/pages/FAQ.tsx",
    find: "scrubbing the bathrooms:",
    replace: "scrubbing and sanitizing the bathrooms:",
    failing: "service copy promises cleaning, not sanitising or disinfecting",
    why: "Claims the standard clean sanitises bathrooms, when the subcontracted cleaners choose their own products.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/components/Navigation.tsx",
    find: 'description: "Military housing move-outs, by phone",',
    replace: 'description: "Military housing, CFHA inspection standards",',
    failing: "the march-out copy works from CFHA's checklist and never claims its standards",
    why: "Claims the march-out clean meets CFHA's standards, which also cover repairs, bulbs and the yard.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/pages/EdmontonMoveInOut.tsx",
    find: 'description: `Walk through the home within ${POLICY.guaranteeWindowHours} hours of the clean and tell us anything missed, and we return',
    replace: 'description: `If the inspection or your own walkthrough finds something missed, say so and we return',
    failing: "a re-clean tied to an inspection is promised only inside the window that runs from the clean",
    why: "Promises a return visit whenever the inspection finds a miss, when the window runs 24 hours from the clean.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/pages/EdmontonMoveInOut.tsx",
    find: "a: `Tell us within ${POLICY.guaranteeWindowHours} hours of the clean and we come back to put it right at no charge. The window runs from the clean, not the inspection, so book the clean as close to the inspection as you can.",
    replace: "a: `Tell us within ${POLICY.guaranteeWindowHours} hours and we come back to put it right at no charge.",
    failing: "a re-clean tied to an inspection is promised only inside the window that runs from the clean",
    why: "Answers an inspection question with a return visit and no window, as the Edmonton move-out FAQ did.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/data/policy.ts",
    find: "`We bring all cleaning supplies and equipment. Optional alternative products",
    replace: "`We bring all cleaning supplies and equipment and disinfect every bathroom. Optional alternative products",
    failing: "service copy promises cleaning, not sanitising or disinfecting",
    why: "Puts a disinfecting claim into the shared service terms, which the page scan alone would never read.",
  },
  {
    guard: "src/data/copy-quality.test.ts",
    target: "src/pages/EdmontonDeepCleaning.tsx",
    find: '"Detailed dusting of vents and the high and low areas',
    replace: '"Detailed dusting of fans, vents and the high and low areas',
    failing: "ceiling fans are an on-request extra, never part of a package",
    why: "Lists fans in the deep package again, as both deep pages did.",
  },
  {
    guard: "src/data/rendered-quality.test.ts",
    target: "dist/edmonton/march-out-cleaning/index.html",
    find: 'href="https://www.canada.ca/en/department-national-defence/services/benefits-military/military-housing/occupant-handbook/moving-out.html"',
    replace: 'href="https://www.canada.ca/"',
    failing: "the pages that state official rules link their official source",
    why: "Drops the CFHA checklist the march-out page works from.",
    dist: true,
  },

  // ---- owner answers, 2026-09-11 (two workflows) ----
  {
    guard: "src/data/area-template-0911.test.ts",
    target: "src/components/GoogleMapEmbed.tsx",
    find: "const [showMap, setShowMap] = useState(false);",
    replace: "const [showMap, setShowMap] = useState(true);",
    failing: "the map embed's first render has no iframe and no Google Maps request",
    why: "Creates the Google Maps iframe on first render again, so every visitor downloads the Maps scripts before interacting.",
  },
  {
    guard: "src/data/area-template-0911.test.ts",
    target: "src/pages/locations/Altadore.tsx",
    find: "<GoogleMapEmbed query=\"Altadore, Calgary, AB\" title=\"Altadore Calgary Service Area Map\" />",
    replace: "<iframe src=\"https://www.google.com/maps?q=Altadore,+Calgary,+AB&output=embed\" width=\"100%\" height=\"450\" style={{ border: 0 }} allowFullScreen loading=\"lazy\" referrerPolicy=\"no-referrer\" title=\"Altadore Calgary Service Area Map\" />",
    failing: "Altadore renders its map through GoogleMapEmbed, with no inline iframe",
    why: "Puts back the inline lazy iframe that the prerender froze into the HTML and that loaded about 405 KiB of Maps scripts on a phone's first load.",
  },
  {
    guard: "src/data/area-template-0911.test.ts",
    target: "src/components/CityRecentCleans.tsx",
    find: "label={`${stars} out of 5 stars`}",
    replace: "label={`Google review`}",
    failing: "every star group is one image named with the review's own rating",
    why: "Names every star row 'Google review' instead of its rating, the label the guard was written to remove.",
  },
  {
    guard: "src/data/area-template-0911.test.ts",
    target: "src/components/CityRecentCleans.tsx",
    find: "const perReview = Boolean(review.sourceUrl?.trim());",
    replace: "const perReview = true;",
    failing: "a review link that opens the branch profile does not claim to open one review",
    why: "Names links that open the branch's general reviews page as if they opened one specific review.",
  },
  {
    guard: "src/data/area-template-0911.test.ts",
    target: "src/components/BeforeAfterGallery.tsx",
    find: "if (pairs.length === 0) return null;",
    replace: "if (pairs.length === 0) return <p>Before-and-after photos from {city} cleans go up here once the homeowners have approved them.</p>;",
    failing: "renders nothing, and no placeholder line, when a city has no approved pairs",
    why: "Restores the placeholder line about photos that do not exist yet.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/CommercialCleaning.tsx",
    find: "const TITLE = \"Office & Commercial Cleaning Edmonton | Duty Cleaners\";",
    replace: "const TITLE = \"Commercial Cleaning Services Edmonton | Duty Cleaners\";",
    failing: "the commercial pages are titled for office and commercial cleaning",
    why: "Restores the old Edmonton commercial title that did not lead with office and commercial cleaning.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/components/CommercialDepth.tsx",
    find: "\"The written quote states the areas, the visit frequency and the pricing basis, per square foot, before work is booked.\"",
    replace: "\"You get the same hourly rate wherever your premises are.\"",
    failing: "commercial pages never quote an hourly rate",
    why: "Brings back hourly-rate wording for commercial work, which the owner prices per square foot at a walkthrough.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/CommercialCleaningCalgary.tsx",
    find: "description: \"Kitchen and dining-area cleaning within the written scope agreed at the walkthrough.\" },",
    replace: "description: \"Commercial kitchen and dining area cleaning that meets health department standards.\" },",
    failing: "no commercial card promises a health department standard",
    why: "Restores the Calgary restaurant card's promise to meet health department standards.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/CommercialCleaningCalgary.tsx",
    find: "const QUOTE_HREF = \"/contact-us/#topic=office&city=calgary\";",
    replace: "const QUOTE_HREF = \"/contact-us/\";",
    failing: "the primary commercial CTA opens office cleaning for the branch's city",
    why: "Points the commercial CTA back at the bare contact form, so Office Cleaning and the city are no longer preselected.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/components/CommercialDepth.tsx",
    find: "to={city === \"Edmonton\" ? \"/pricing/\" : \"/calgary/pricing/\"}",
    replace: "to={city === \"Edmonton\" ? \"/\" : \"/cleaning-services-calgary/\"}",
    failing: "the residential-pricing link goes to the branch's price list",
    why: "Sends 'See residential pricing' back to the city hubs instead of the price lists.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/BlogHouseCleaningCost.tsx",
    find: "At Duty Cleaners, whole-home standard, deep and move-out cleans are priced flat by home size, so the price stays the same",
    replace: "Duty Cleaners does not charge by the hour for a home clean: standard, deep and move-out cleans are priced flat by home size, so the price stays the same",
    failing: "the cost guide no longer says home cleans are never hourly",
    why: "Restores the false claim that no home cleaning is hourly, when partial jobs are quoted from HOME_HOURLY_RATE.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/BlogHouseCleaningCost.tsx",
    find: "quoted by the hour from ${HOME_HOURLY} per cleaner-hour",
    replace: "quoted by the hour from ${HOURLY} per cleaner-hour",
    failing: "the cost guide's hourly answer quotes the home rate for home jobs and the Airbnb rate for turnovers",
    why: "Swaps in the Airbnb-only rate for home hourly jobs, the swap the owner forbade.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/BlogHouseCleaningCost.tsx",
    find: "fridge, window sills and tracks wiped, and baseboards",
    replace: "fridge, window tracks and reachable interior glass, and baseboards",
    failing: "the cost guide's move-out card leaves interior glass to the add-ons",
    why: "Puts interior glass back into the move-out scope, when interior window cleaning is a paid add-on.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/pages/CalgaryMoveInOut.tsx",
    find: "landlord must return the deposit, or return what is left with a written statement of",
    replace: "security deposit must be returned. Any balance comes with a written statement of",
    failing: "no page states the 10-day deposit rule without the deductions it allows",
    why: "Restores the too-broad 'deposit must be returned within 10 days' sentence that leaves out the statement of deductions Alberta's rules allow.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "public/llms.txt",
    find: "- Optional alternative products available as a $15 add-on, before GST",
    replace: "- Eco-friendly products available as a $15 add-on, before GST",
    failing: "no page, data file or llms file sells eco-friendly or green products",
    why: "Puts the unsubstantiated eco-friendly label back on the machine-reader surface, when subcontractors choose their own products.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/components/LocationPricing.tsx",
    find: "from one bedroom to five, a deep",
    replace: "from one bedroom to five or more bedrooms, a deep",
    failing: "no page describes the top tier as five or more bedrooms",
    why: "Calls the top table row five-or-more when six and seven bedrooms cost more and are priced in the quote form.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/pages/locations/Leduc.tsx",
    find: "for five bedrooms, flat, before GST",
    replace: "for five bedrooms or more, flat, before GST",
    failing: "no page describes the top tier as five or more bedrooms",
    why: "The exact wording that sat on Leduc, Morinville and the Calgary move-out FAQ until 2026-09-18: the first pattern only knew 'five or more', so 'five bedrooms or more' passed.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/data/pricing.ts",
    find: "\"Window sills and tracks wiped\",",
    replace: "\"Window tracks and reachable interior glass\",",
    failing: "the move-out inclusions leave interior windows and walls to the add-ons",
    why: "Lists interior glass as included in a move-out, when interior window cleaning is a paid add-on.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/pages/EdmontonPricing.tsx",
    find: "const addOnServices = addOnTableRows(\"edmonton\");",
    replace: "const addOnServices = addOnTableRows(\"edmonton\").filter((row) => !/garage/i.test(row.service));",
    failing: "the Edmonton price list shows the balcony / garage sweep add-on",
    why: "Filters the real balcony / garage sweep add-on back out of the Edmonton add-on table.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/pages/EdmontonServices.tsx",
    find: "\"Inside all cabinets, drawers and closets\",",
    replace: "\"Inside all cabinets, drawers, and the kitchen walls\",",
    failing: "the Edmonton services page lists no kitchen walls in a move-out",
    why: "Puts walls back into the Edmonton move-out card, when wall washing is an add-on.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/lib/tracking.ts",
    find: "  if (pageService && choicePath !== pathname + search) return pageService;",
    replace: "  if (pageService && choicePath === null) return pageService;",
    failing: "a bare #quote on the Calgary move-out page drops a Standard chosen on another page",
    why: "Lets a service chosen on another page win over the move-out page's own service again, which is the reviewer's bug.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/components/quote/QuoteFlow.tsx",
    find: "    const next = serviceOnOpen({",
    replace: "    const next = (({ current }) => current)({",
    failing: "QuoteFlow decides the service on every open, not only when initialService changes",
    why: "Stops QuoteFlow from asking serviceOnOpen() on each open, so the flow keeps its stale service.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/lib/analytics.ts",
    find: "      if (EMAIL_VALUE.test(text) || PHONE_VALUE.test(text) || POSTAL_VALUE.test(text)) continue;",
    replace: "      if (POSTAL_VALUE.test(text)) continue;",
    failing: "drops personal keys, personal-looking values and free text",
    why: "Removes the email and phone value checks, so a phone number under an allowed key reaches analytics.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/lib/analytics.ts",
    find: "  if (!GA4_ID.test(id)) return false;",
    replace: "  if (id === \"UA-12345-1\") return false;",
    failing: "loads nothing when no measurement ID is set",
    why: "Makes the GA4 loader inject gtag.js even when VITE_GA4_MEASUREMENT_ID is unset.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/components/quote/PricePanel.tsx",
    find: "    ? `${formatPrice(quote.firstClean)}–${formatPrice(quote.rangeHigh)}`",
    replace: "    ? `${formatPrice(quote.rangeLow)}–${formatPrice(quote.rangeHigh)}`",
    failing: "an estimate never quotes below BookingKoala's own tier price",
    why: "Restores the invented -10% low end, quoting $495 for a post-construction tier BookingKoala prices at $550.",
  },
  {
    guard: "src/data/headers.test.ts",
    target: "public/_headers",
    find: " https://api.bookin60.com https://www.googletagmanager.com; style-src",
    replace: " https://api.bookin60.com; style-src",
    failing: "allows the Google Analytics 4 loader's origins in the directives it uses",
    why: "Drops gtag.js's origin from script-src, which would block the GA4 loader once the CSP is enforced.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/Contact.tsx",
    find: "const presetCity = topicCity === \"edmonton\" || topicCity === \"calgary\" ? topicCity : \"\";",
    replace: "const presetCity = \"\";",
    failing: "preselects office or Airbnb and the city, and drops the home-pricing pitch",
    why: "Stops the contact form preselecting the branch's city for visitors sent from the commercial and Airbnb pages.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/Contact.tsx",
    find: "const untouched = !prev.message.trim() || prev.message === previousPreset;",
    replace: "const untouched = !prev.message.trim();",
    failing: "a topic link followed on the contact page replaces an unedited preset message",
    why: "Leaves the previous topic's preset message in place when a visitor already on /contact-us/ follows a different topic link, so the service and the message disagree.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/Contact.tsx",
    find: "Request a Callback",
    replace: "See My Instant Price",
    failing: "office and Airbnb visitors are not pointed at the instant price anywhere on the page",
    why: "Brings back the instant-price push in the hero for office and Airbnb visitors, whose jobs have no instant price.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/CommercialCleaning.tsx",
    find: "Office cleaning can be requested with the quote form. Warehouse, retail, medical,",
    replace: "Every kind of premises can be requested with the quote form. Warehouse, retail, medical,",
    failing: "premises other than offices are scoped by phone, not quoted online",
    why: "Implies warehouse, retail, medical, restaurant and gym work is quoted online, when the owner quotes only office cleaning online.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/CommercialCleaning.tsx",
    find: "the clinic's own product and waste-handling requirements, which a general office scope does not cover. They are",
    replace: "disinfection and waste handling that a general office scope does not cover. They are",
    failing: "commercial copy says what the team does, not what a product does",
    why: "Restores the claim that the team handles disinfection in medical space, when the subcontracted cleaners choose their own products.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/BlogHouseCleaningCost.tsx",
    find: "published them: before GST, including GST, or not saying. Your own quote may differ.",
    replace: "published them, before GST; your own quote may differ.",
    failing: "the cost guide dates and sources its market ranges",
    why: "Calls the whole market sample \"before GST\" when one company includes GST and two do not say.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/BlogHouseCleaningCost.tsx",
    find: "moveOutTwoBedroom: [199, 387],",
    replace: "moveOutTwoBedroom: [199, 650],",
    failing: "the cost guide's market ranges match the recorded price sample",
    why: "Brings back a 2-bedroom move-out high end taken from one company's any-size starting price, which disagrees with the recorded sample.",
  },
  {
    guard: "src/data/area-template-0911.test.ts",
    target: "src/pages/locations/West.tsx",
    find: "<GoogleMapEmbed query=\"West Calgary, AB\" title=\"West Calgary Service Area Map\" />",
    replace: "<iframe src=\"https://www.google.com/maps?q=West+Calgary,+AB&output=embed\" width=\"100%\" height=\"450\" style={{ border: 0 }} loading=\"lazy\" title=\"West Calgary Service Area Map\" />",
    failing: "no location page ships an inline Google Maps iframe",
    why: "Puts back the inline lazy Google Maps iframe that loaded about 405 KiB of Maps scripts on first paint, the defect 93 location pages carried.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/pages/locations/Bannerman.tsx",
    find: "before GST: ${POLICY.ecoProductsHowToRequest}.`,",
    replace: "before GST: ask the office which products are available and suitable for your surfaces when you book.`,",
    failing: "location pages take the alternative-products request from policy.ts, with the fee before GST",
    why: "Hand-types the owner's alternative-products request clause again instead of reading it from policy.ts.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/lib/bk-extras.ts",
    find: "[\"sweep only of garage\", \"A sweep only, not a full garage clean; offered mostly in summer, when the weather allows\"],",
    replace: "[\"sweep only of garage\", \"Sweep-out only\"],",
    failing: "the balcony / garage sweep says it is a sweep only, in season",
    why: "Restores the sweep add-on line that neither says it is not a full garage clean nor gives its summer season.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/pages/BlogChoosingCleaningCompany.tsx",
    find: "upholstery or exterior windows, so those jobs need a specialist. It does not clean garages either: the only garage work is a balcony or garage sweep add-on, offered mostly in summer when the weather allows.",
    replace: "upholstery, exterior windows or garages, so those jobs need a specialist.",
    failing: "no location page or blog post excludes garages without naming the sweep add-on",
    why: "Brings back the blanket garage exclusion that hides the owner's balcony or garage sweep add-on.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/data/pricing.ts",
    find: "price: formatCents(q.ongoing ?? q.firstClean)",
    replace: "price: formatPrice(q.ongoing ?? q.firstClean)",
    failing: "the recurring visit table prints every price with cents",
    why: "Lets the recurring table print whole-dollar visits as '$227' next to '$123.99' again.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/lib/analytics.ts",
    find: "return (PRODUCTION_HOSTS as readonly string[]).includes(host);",
    replace: "return host !== \"\";",
    failing: "loads only on dutycleaners.ca and www.dutycleaners.ca, so previews record nothing",
    why: "Lets the Netlify preview and localhost load Google Analytics and record visits.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/lib/analytics.ts",
    find: "const query = kept.toString();",
    replace: "const query = url.searchParams.toString();",
    failing: "sends its own page_view with the query string removed, campaign tags kept",
    why: "Sends the full query string, with any name, email, phone or postal code in it, to Google as page_location.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/components/quote/BookingHandoff.tsx",
    find: "onClick={() => window.location.assign(bookingUrl)}",
    replace: "href={bookingUrl}",
    failing: "the BookingKoala URL is never a link's href",
    why: "Puts the prefilled BookingKoala URL back on a link, where GA4's outbound-click capture records it.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/components/quote/QuoteFlow.tsx",
    find: "if (pendingServiceRef.current !== null && pendingServiceRef.current !== service) return;",
    replace: "if (false) return;",
    failing: "quote_step waits for the service an open switched to",
    why: "Reports quote_step and quote_price_view with the service from before the open switched it.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/lib/tracking.ts",
    find: "if (pageService && choicePath !== pathname + search) return pageService;",
    replace: "if (pageService && choicePath !== pathname) return pageService;",
    failing: "a ?service= link to the same path wins over an in-flow choice made there without it",
    why: "Lets a stale in-flow choice beat an explicit ?service= link to the same path.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/components/QuoteOverlay.tsx",
    find: "{RATING_CLAIM}",
    replace: "4.9 on Google",
    failing: "no hand-typed rating or phone number",
    why: "Hand-types the Google rating in the quote overlay instead of reading it from proof.ts.",
  },
  {
    guard: "src/lib/booking-redirect.test.ts",
    target: "src/lib/booking-redirect.ts",
    find: "T1Y: \"Calgary\",",
    replace: "T1Y: null,",
    failing: "counts T1Y (Rundle, Whitehorn, Monterey Park) as Calgary, with no travel fee",
    why: "Charges north-east Calgary (T1Y) the out-of-city travel fee.",
  },
  {
    guard: "src/lib/booking-redirect.test.ts",
    target: "src/lib/booking-redirect.ts",
    find: "T3Z: null,",
    replace: "T3Z: \"Calgary\",",
    failing: "charges T3Z (Redwood Meadows, Bragg Creek) the travel fee: it lies outside Calgary",
    why: "Exempts Redwood Meadows and Bragg Creek (T3Z, outside Calgary) from the travel fee.",
  },

  // ---- Red Deer branch and commercial terms, 2026-09-11 ----
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/pages/CommercialCleaning.tsx",
    find: "                    <Link to={QUOTE_HREF}>Request an Office Cleaning Quote</Link>",
    replace: "                    <Link to={QUOTE_HREF}>Request a Commercial Cleaning Quote</Link>",
    failing: "the primary commercial CTA opens office cleaning for the branch's city",
    why: "Puts back the old closing-CTA label, which offers a commercial quote online when the form quotes only office cleaning. The find has 20 leading spaces, so it matches only the closing CTA; the hero line has 18.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/components/CommercialDepth.tsx",
    find: "and evening and weekend visits outside the ${city} office's regular hours can be arranged.",
    replace: "and times outside the ${city} office's regular hours can be discussed at the walkthrough.",
    failing: "the commercial FAQ says evening and weekend work can be arranged",
    why: "Brings back the walkthrough hedge in place of the owner's plain yes to evening and weekend work.",
  },
  {
    guard: "src/data/commercial-costguide-0911.test.ts",
    target: "src/components/CommercialDepth.tsx",
    find: "inside that window the fee is ${POLICY.cancellationFee}.",
    replace: "inside that window the fee is $50.",
    failing: "the commercial FAQ applies the home cancellation fee and re-clean window, read from policy.ts",
    why: "Hand-types the late-cancellation fee into the commercial FAQ instead of reading POLICY.cancellationFee, so a policy change would leave the commercial pages stale.",
  },
  {
    guard: "src/data/red-deer-branch.test.ts",
    target: "src/data/legacy-urls.ts",
    find: "{ legacy: \"/cleaning-services-red-deer\", target: \"/locations/red-deer\", mode: \"preserve\", impressions: 600 },",
    replace: "{ legacy: \"/cleaning-services-red-deer\", target: \"/locations\", mode: \"redirect\", impressions: 600 },",
    failing: "the Red Deer page route exists and the legacy redirect is gone",
    why: "Turns the Red Deer listing's Website URL back into a 301 to /locations/.",
  },
  {
    guard: "src/data/red-deer-branch.test.ts",
    target: "src/lib/city-from-path.ts",
    find: "\"/cleaning-services-red-deer\",",
    replace: "\"/cleaning-services-red-deer-old\",",
    failing: "the Red Deer URL resolves to the Red Deer office and nothing else moves",
    why: "Makes the Red Deer page resolve to the Edmonton office, so its chrome and quote flow show Edmonton's phone.",
  },
  {
    guard: "src/data/red-deer-branch.test.ts",
    target: "src/data/proof.ts",
    find: "phone: \"(587) 570-6979\",",
    replace: "phone: \"(403) 768-1341\",",
    failing: "proof.ts Red Deer NAP, pin and hours equal the Google listing",
    why: "Publishes a Red Deer phone that is not the Google listing's number.",
  },
  {
    guard: "src/data/red-deer-branch.test.ts",
    target: "src/data/proof.ts",
    find: "{ days: [\"Sunday\"], opens: \"09:00\", closes: \"15:00\" },",
    replace: "{ days: [\"Sunday\"], opens: \"10:00\", closes: \"15:00\" },",
    failing: "the Edmonton and Calgary hours are unchanged by the per-branch model",
    why: "Lets the per-branch hours model drift the Edmonton and Calgary Sunday hours.",
  },
  {
    guard: "src/data/red-deer-branch.test.ts",
    target: "src/data/proof.ts",
    find: "googleRating: null,",
    replace: "googleRating: confirm(4.9, { by: \"google-listing\", on: \"2026-09-11\" }),",
    failing: "the Red Deer page never renders RATING_CLAIM or a review count",
    why: "Records a rating for the Red Deer listing, which has no reviews.",
  },
  {
    guard: "src/data/red-deer-branch.test.ts",
    target: "src/pages/locations/RedDeer.tsx",
    find: "{ icon: CheckCircle2, text: \"Pay after your clean\" },",
    replace: "{ icon: CheckCircle2, text: RATING_CLAIM },",
    failing: "the Red Deer page never renders RATING_CLAIM or a review count",
    why: "Puts the Edmonton and Calgary listings' 4.9 on the Red Deer page as if it were Red Deer's.",
  },
  {
    guard: "src/data/red-deer-branch.test.ts",
    target: "src/lib/booking-redirect.ts",
    find: "const RED_DEER_FSAS = [\"T4N\", \"T4P\", \"T4R\"];",
    replace: "const RED_DEER_FSAS: string[] = [];",
    failing: "Red Deer FSAs add no travel fee",
    why: "Charges Red Deer addresses the outside-city travel fee although the branch has its own office.",
  },
  {
    guard: "src/data/red-deer-branch.test.ts",
    target: "src/lib/booking-redirect.ts",
    find: "T3Z: null,",
    replace: "T3Z: null,\n  T3T: null,",
    failing: "T3T (Tsuut'ina Nation) adds no travel fee",
    why: "Charges Tsuut'ina Nation addresses the travel fee, which the owner said they do not pay.",
  },
  {
    guard: "src/data/red-deer-branch.test.ts",
    target: "index.html",
    find: "\"@id\": \"https://dutycleaners.ca/#reddeer\", \"@type\": \"LocalBusiness\"",
    replace: "\"@id\": \"https://dutycleaners.ca/#red-deer\", \"@type\": \"LocalBusiness\"",
    failing: "the Organization schema lists the Red Deer branch",
    why: "Detaches the Organization's subOrganization from the Red Deer branch entity's @id.",
  },
  {
    guard: "src/data/owner-answers-0911.test.ts",
    target: "src/pages/Locations.tsx",
    find: "office, on {CITY_PROOF.reddeer.phone}, with no travel fee",
    replace: "office, on {CITY_PROOF.reddeer.phone}. Duty Cleaners does not serve Red Deer, with no travel fee",
    failing: "nothing says Red Deer is not served",
    why: "Restores a 'does not serve Red Deer' line the owner contradicted on 2026-09-11.",
  },
  {
    guard: "src/data/quote-funnel-0911.test.ts",
    target: "src/components/quote/QuoteFlow.tsx",
    find: "const outsideCity = cityStatus === \"unknown\" ? insideCity === false : cityStatus === \"outside\";",
    replace: "const outsideCity = !isRedDeerPostalCode(details.postalCode) && (cityStatus === \"unknown\" ? insideCity === false : cityStatus === \"outside\");",
    failing: "QuoteFlow has no Red Deer exception to the travel fee or the booking link",
    why: "Reintroduces the interim Red Deer special case that kept Red Deer codes off the normal booking path.",
  },
  {
    guard: "src/lib/booking-redirect.test.ts",
    target: "src/lib/booking-redirect.ts",
    find: "const RED_DEER_FSAS = [\"T4N\", \"T4P\", \"T4R\"];",
    replace: "const RED_DEER_FSAS = [\"T4N\", \"T4P\", \"T4R\", \"T4S\"];",
    failing: "keeps T4S (Sylvan Lake and Red Deer County) and the other T4 codes outside",
    why: "Waives the travel fee for T4S, whose land is 89% outside Red Deer (Red Deer County).",
  },
  {
    guard: "src/lib/booking-redirect.test.ts",
    target: "src/lib/booking-redirect.ts",
    find: "T3Z: null,",
    replace: "T3Z: null,\n  T3T: null,",
    failing: "adds no travel fee for a T3T postal code",
    why: "Charges Tsuut'ina Nation (T3T) addresses the travel fee.",
  },
  {
    guard: "src/data/structured-data.test.ts",
    target: "dist/cleaning-services-red-deer/index.html",
    find: "\"latitude\":52.2673285",
    replace: "\"latitude\":52.26",
    failing: "the hub's LocalBusiness geo equals proof.ts",
    why: "Publishes a Red Deer office pin that is not the Google listing's. NOT VERIFIED: needs dist: true and a build and prerender first.",
    dist: true,
  },
  {
    guard: "src/data/internal-links.test.ts",
    target: "dist/cleaning-services-red-deer/index.html",
    find: "hover:text-accent\" href=\"/edmonton/deep-cleaning/\"",
    replace: "hover:text-accent\" href=\"/calgary/deep-cleaning/\"",
    failing: "no location page links to the other city's service pages",
    why: "Makes the Red Deer page link the Calgary service set. NOT VERIFIED: needs dist: true and a build; confirm the find occurs once in the prerendered page (the card link's class ends in hover:text-accent; the footer's deep-cleaning link has a different class).",
    dist: true,
  },
  // ---- AuditSpur findings, 2026-09-11 ----
  {
    guard: "src/data/auditspur-0911.test.ts",
    target: "src/pages/BlogHouseCleaningCost.tsx",
    find: "h2: \"What changes the price of a house cleaning?\",",
    replace: "h2: \"What changes the price\",",
    failing: "every cost-guide FAQ question is a visible section heading",
    why: "Leaves a marked-up FAQ question that the page never shows, as three were.",
  },
  {
    guard: "src/data/auditspur-0911.test.ts",
    target: "src/pages/Contact.tsx",
    find: "<form id=\"contact-form\" method=\"post\" onSubmit={handleSubmit}",
    replace: "<form id=\"contact-form\" onSubmit={handleSubmit}",
    failing: "lead forms post, so a native submit never puts personal data in the URL",
    why: "Lets a native submit of the contact form put a name and phone number in the URL.",
  },
  {
    guard: "src/data/auditspur-0911.test.ts",
    target: "src/pages/BlogCleaningProducts.tsx",
    find: "          image: absoluteAssetUrl(heroImage.img.src),",
    replace: "          image: \"https://dutycleaners.ca/og-image.jpg\",",
    failing: "the product post's schema image is its own hero image",
    why: "Makes the post's schema image disagree with its og:image again.",
  },
  {
    guard: "src/data/auditspur-0911.test.ts",
    target: "src/pages/Blog.tsx",
    find: "                  : POST_MODIFIED[p.slug!.replace(/\\/+$/, \"\")]\n                    ? { dateModified: POST_MODIFIED[p.slug!.replace(/\\/+$/, \"\")] }\n                    : {}),",
    replace: "                  : {}),",
    failing: "the blog index states a revision date for posts with no known publication date",
    why: "Drops the revision date from the four index entries whose publication date is unknown.",
  },
  {
    guard: "src/data/auditspur-0911.test.ts",
    target: "public/.well-known/security.txt",
    find: "Contact: mailto:support@dutycleaners.ca\n",
    replace: "",
    failing: "security.txt names a contact and has not expired",
    why: "Publishes a security.txt with no contact, which defeats its purpose.",
  },
  {
    guard: "src/data/auditspur-0911.test.ts",
    target: "public/robots.txt",
    find: "User-agent: Amzn-SearchBot",
    replace: "User-agent: Amzn-SearchBot-Retired",
    failing: "robots.txt keeps Amazonbot out and lets Amazon's search crawlers in",
    why: "Shuts Amazon's Alexa search crawler out along with its training crawler.",
  },
  {
    guard: "src/data/auditspur-0911.test.ts",
    target: "index.html",
    find: "        \"knowsAbout\": [\n",
    replace: "        \"knowsAboutX\": [\n",
    failing: "the Organization names the services it sells",
    why: "Removes the Organization's knowsAbout list.",
  },
  // ---- AuditSpur findings, 2026-09-11 16:21 ----
  {
    guard: "src/data/auditspur-1621.test.ts",
    target: "dist/edmonton/march-out-cleaning/index.html",
    find: ',"openingHoursSpecification":[{"@type":"OpeningHoursSpecification","dayOfWeek":["Monday"',
    replace: ',"openingHoursSpecificationX":[{"@type":"OpeningHoursSpecification","dayOfWeek":["Monday"',
    failing: "every LocalBusiness the site publishes says when it is open",
    why: "Puts back a branch node that never says when it answers, as 21 nodes did.",
    dist: true,
  },
  {
    guard: "src/data/auditspur-1621.test.ts",
    target: "src/pages/EdmontonMarchOut.tsx",
    find: 'openingHours: openingHoursShortFor("edmonton"),',
    replace: 'openingHours: ["Mo-Sa 08:00-20:00", "Su 09:00-15:00"],',
    failing: "the office hours and address are read from proof.ts, never retyped",
    why: "Retypes the hours next to proof.ts, the copy that goes stale the day the office changes them.",
  },
  {
    guard: "src/data/auditspur-1621.test.ts",
    target: "index.html",
    find: '"name": "Duty Cleaners Calgary"',
    replace: '"name": "Duty Cleaners Calgary Cleaning"',
    failing: "the Organization's branch references name the entity they point at",
    why: "Drifts a branch name hand-typed in static HTML away from data/proof.ts, which is exactly what that file cannot import.",
  },
  {
    guard: "src/lib/booking-redirect.test.ts",
    target: "src/lib/booking-redirect.ts",
    find: 'if (!normalized.startsWith("T")) return "unknown";',
    replace: 'if (false) return "unknown";',
    failing: "does not price another province's code as an Alberta suburb",
    why: "Calls a Toronto or Vancouver postal code an outside-city address, which is a claim that we serve it for a travel fee.",
  },
  // ---- third-party embeds settle to their loaded state, 2026-09-17 ----
  {
    guard: "src/data/prerender-embeds.test.ts",
    target: "scripts/settle-embeds.mjs",
    find: "return tag.replace('aria-busy=\"true\"', 'aria-busy=\"false\"');",
    replace: "return tag;",
    failing: "settles a snapshot caught mid-load into exactly the loaded bytes",
    why: "Leaves a mid-load embed aria-busy, so the snapshot depends on whether BookingKoala answered before the prerender did.",
  },
  {
    guard: "src/data/prerender-embeds.test.ts",
    target: "dist/gift-card/index.html",
    find: 'data-embed-frame="true"',
    replace: 'data-embed-framex="true"',
    failing: "the gift-card page ships a visible purchase form",
    why: "Drops the gift-card iframe's marker, which would let the frozen-embed check pass without examining anything.",
    dist: true,
  },
  // ---- the /assets/ cache scope, found live on SiteGround, 2026-09-17 ----
  {
    guard: "src/data/htaccess-cache-scope.test.ts",
    target: "public/.htaccess",
    find: '    Header set Cache-Control "public, max-age=3600, must-revalidate" env=!DUTY_HASHED_ASSET',
    replace: '    Header set Cache-Control "public, max-age=3600, must-revalidate"',
    failing: "the immutable and the hourly Cache-Control sit in the SAME FilesMatch, split only by env=",
    why: "Drops the env=! condition, which is the exact shape of the bug this guard exists to catch: a Header set that is not actually scoped to non-asset files.",
  },
  // ---- 2026-09-17: Google figures, their fingerprint, and HSTS ------------
  {
    guard: "src/data/llms-txt.test.ts",
    target: "public/llms.txt",
    find: "read from the listings themselves on 2026-09-17",
    replace: "read from the listings themselves on 2026-09-01",
    failing: "llms.txt states the date the counts were read",
    why: "Leaves the counts right and the read date stale, the gap the numbers-only guard cannot see.",
  },
  {
    guard: "src/data/policy.test.ts",
    target: "src/data/proof.ts",
    find: 'googleReviewCount: confirm(238, { by: "google-listing", on: "2026-09-17"',
    replace: 'googleReviewCount: confirm(238, { by: "google-listing", on: "2026-01-17"',
    failing: "the Google figures were re-read within the last 90 days",
    why: "Backdates one read past the quarterly window.",
  },
  {
    guard: "src/data/seo-editorial.test.ts",
    target: "scripts/content-revisions.ts",
    find: '/\\b\\d[\\d,]*(\\s+(?:Edmonton',
    replace: '/\\bNEVER\\d[\\d,]*(\\s+(?:Edmonton',
    failing: "does not change a revision date when a Google review count is re-read",
    why: "Makes the count mask match nothing (a $-free break: the prover, like String.replace, would expand $& in a replacement), so a re-read re-dates every page that prints the count.",
  },
  {
    guard: "src/data/htaccess-parity.test.ts",
    target: "public/.htaccess",
    find: 'Header always set Strict-Transport-Security "max-age=86400" env=DUTY_PRODUCTION_HOST',
    replace: 'Header always set Strict-Transport-Security "max-age=86400; includeSubDomains; preload"',
    failing: "carries the security headers and scopes HSTS to the production host, without includeSubDomains or preload",
    why: "Drops the host scope and adds the two directives the owner deferred: pins the test host and every subdomain.",
  },
  // ---- 2026-09-17: branch-neutral chrome and the remembered branch --------
  {
    guard: "src/data/branch-preference.test.ts",
    target: "src/lib/city-from-path.ts",
    find: "  \"/about-us\",",
    replace: "  \"/about-us-gone\",",
    failing: "a page that belongs to no branch resolves to null",
    why: "Drops About from the neutral set, so it falls back to Edmonton like it used to.",
  },
  {
    guard: "src/data/branch-preference.test.ts",
    target: "src/lib/branch-preference.ts",
    find: "if (seen === \"edmonton\" && current === \"reddeer\") return \"reddeer\";",
    replace: "if (seen === \"never\" && current === \"reddeer\") return \"reddeer\";",
    failing: "an Edmonton page never overwrites a Red Deer choice",
    why: "Lets the shared Edmonton pages turn a Red Deer visitor into an Edmonton one.",
  },
  {
    guard: "src/data/branch-preference.test.ts",
    target: "dist/about-us/index.html",
    find: ">Call us<",
    replace: ">Call<",
    failing: "every branch-less page offers every office in its header",
    why: "Removes the Call us menu from a neutral page's prerendered header.",
    dist: true,
  },
  {
    guard: "src/data/branch-preference.test.ts",
    target: "dist/cleaning-services-calgary/index.html",
    find: "href=\"tel:4037681341\" class=\"inline-flex min-h-[44px]",
    replace: "href=\"tel:7809136565\" class=\"inline-flex min-h-[44px]",
    failing: "a page that belongs to a branch shows only that office in its header",
    why: "Puts the Edmonton office in the Calgary hub's header, the original bug in reverse.",
    dist: true,
  },
  {
    guard: "src/data/branch-preference.test.ts",
    target: "dist/about-us/index.html",
    find: ">Call an office<",
    replace: ">Call (780) 913-6565<",
    failing: "a neutral page's own call button names no single office",
    why: "Puts the Edmonton number back into About's hero button, the original bias one level below the header.",
    dist: true,
  },
  {
    guard: "src/data/branch-preference.test.ts",
    target: "dist/privacy-policy/index.html",
    find: "whose pages you last looked at",
    replace: "whose pages you last visited",
    failing: "the privacy policy names the remembered-office preference",
    why: "Reworded so the disclosure the guard looks for is gone.",
    dist: true,
  },
  // ---- crawl hygiene: intent in the fragment (2026-09-17) ------------------
  {
    guard: "src/data/crawl-hygiene.test.ts",
    target: "dist/cleaning-services-red-deer/index.html",
    find: 'href="/contact-us/#city=reddeer"',
    replace: 'href="/contact-us/?city=reddeer"',
    failing: "no built page links to an internal URL with a query string",
    why: "Puts the Red Deer contact link back in the query form a crawler fetches as its own page.",
    dist: true,
  },
  {
    guard: "src/data/crawl-hygiene.test.ts",
    target: "dist/cleaning-services-red-deer/index.html",
    find: 'href="/contact-us/#topic=office&amp;city=reddeer"',
    replace: 'href="/contact-us/"',
    failing: "the deep-clean and contact intents are still carried, in the fragment",
    why: "Drops the office topic from the Red Deer link, so the form would open blank.",
    dist: true,
  },
  {
    guard: "src/data/crawl-hygiene.test.ts",
    target: "src/lib/url-intent.ts",
    find: '  return body.split("&").find((token) => token && !token.includes("=")) ?? "";',
    replace: '  return "";',
    failing: "the readers merge the fragment over the query string, and the anchor stays readable",
    why: "Makes every fragment anchorless, so #quote&intent=deep would scroll instead of opening the quote.",
  },
  {
    guard: "src/data/crawl-hygiene.test.ts",
    target: "src/pages/Contact.tsx",
    find: "const searchParams = intentParams(search, hash);",
    replace: 'const searchParams = intentParams(search, "");',
    failing: "the contact form and the quote overlay read the fragment",
    why: "Stops the contact form reading the fragment, so #topic=office would open a blank form.",
  },
  // ---- the branch office pin on every branch node (scan 1131, 2026-09-17) ---
  {
    guard: "src/data/branch-geo.test.ts",
    target: "dist/cleaning-services-leduc/index.html",
    find: '"latitude":53.504317,"longitude":-113.64391',
    replace: '"latitude":53.6,"longitude":-113.64391',
    failing: "every branch node with an address carries that branch's office pin",
    why: "Moves the Edmonton branch's pin on the Leduc page off the office, so one page's branch node points somewhere else.",
    dist: true,
  },
  {
    guard: "src/data/branch-geo.test.ts",
    target: "dist/edmonton/march-out-cleaning/index.html",
    find: '"image":"https://dutycleaners.ca/og-image.jpg"',
    replace: '"imageless":"https://dutycleaners.ca/og-image.jpg"',
    failing: "the march-out provider carries what the shared builders publish",
    why: "Strips the image the march-out provider gained, back to the drifted shape scan 1131 found.",
    dist: true,
  },
  // ---- responsive content images (scan 1131, 2026-09-17) --------------------
  {
    guard: "src/data/responsive-images.test.ts",
    target: "dist/edmonton/march-out-cleaning/index.html",
    find: ' sizes="100vw"',
    replace: ' data-sizes="100vw"',
    failing: "every content image on the pages scan 1131 named has a srcset, sizes, width and height",
    why: "Takes the sizes hint off the march-out hero, so the browser would pick a candidate for a 100vw slot with no idea of the slot.",
    dist: true,
  },
  {
    guard: "src/data/responsive-images.test.ts",
    target: "dist/blog/cleaning-schedule/index.html",
    find: 'width="1024" height="576" alt="Woman wiping a counter',
    replace: 'width="1000" height="576" alt="Woman wiping a counter',
    failing: "no srcset candidate is wider than the image's own intrinsic width",
    why: "Declares the hero narrower than its 1024w candidate, the shape of an upscaled variant.",
    dist: true,
  },
  {
    guard: "src/data/responsive-images.test.ts",
    target: "src/components/ResponsiveImage.tsx",
    find: '  full: "100vw",',
    replace: '  full: "100vw, 100vw",',
    failing: "the sizes presets describe the layouts they are named for",
    why: "Corrupts the full-bleed preset into a string no browser parses as intended.",
  },
  // ---- and this registry itself ------------------------------------------
  {
    guard: "src/data/guard-proofs.test.ts",
    target: "scripts/guard-proofs.ts",
    find: 'find: \'legacy: "/cleaning-services-for-leduc-ab"\',',
    replace: 'find: \'legacy: "/cleaning-services-for-leduc-ab-gone"\',',
    failing: "every proof's find string occurs exactly once in its target",
    why: "A proof whose find string no longer exists would restore nothing and prove nothing.",
  },
];
