import re,sys,html
sys.stdout.reconfigure(encoding='utf-8')
p=sys.argv[1]
s=open(p,encoding='utf-8').read()
body=s
body=re.sub(r'<script.*?</script>','',body,flags=re.S)
body=re.sub(r'<style.*?</style>','',body,flags=re.S)
body=re.sub(r'<svg.*?</svg>',' ',body,flags=re.S)
body=re.sub(r'<!--.*?-->','',body,flags=re.S)
body=re.sub(r'<a\b([^>]*)>',lambda m:'\n[LINK '+(re.search(r'href="([^"]*)"',m.group(1)).group(1) if re.search(r'href="([^"]*)"',m.group(1)) else '?')+'] ',body)
body=re.sub(r'</a>',' [/L]\n',body)
body=re.sub(r'<button\b[^>]*>','\n[BTN] ',body)
body=re.sub(r'</button>',' [/B]\n',body)
body=re.sub(r'<(h[1-6])\b[^>]*>',lambda m:'\n\n<'+m.group(1).upper()+'> ',body)
body=re.sub(r'</h[1-6]>','\n',body)
body=re.sub(r'<img\b([^>]*?)/?>',lambda m:'[IMG alt="'+(re.search(r'alt="([^"]*)"',m.group(1)).group(1) if re.search(r'alt="([^"]*)"',m.group(1)) else 'NONE')+'"]',body)
body=re.sub(r'<(li|p|div|tr|section|br|summary|details)\b[^>]*>','\n',body)
body=re.sub(r'<t[dh]\b[^>]*>',' | ',body)
body=re.sub(r'<[^>]+>','',body)
body=html.unescape(body)
body=re.sub(r'[ \t]+',' ',body)
body=re.sub(r'\n\s*\n\s*\n+','\n\n',body)
print(body.strip())
